apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: bidrag-dokument-arkiv
  labels:
    team: bidrag
spec:
  image: repo.adeo.no:5443/bidrag-dokument-arkiv:{{version}}
  port: 8080
  liveness:
    path: /bidrag-dokument-arkiv/actuator/health
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /bidrag-dokument-arkiv/actuator/health
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /bidrag-dokument-arkiv/actuator/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  ingresses:
    - https://bidrag-dokument-arkiv.nais.adeo.no/
  vault:
    enabled: true