apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{name}}
  namespace: bidrag
  labels:
    team: bidrag
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "512m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  image: {{image}}
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
  webproxy: true
  accessPolicy:
    inbound:
      rules:
      {{#each azureAccessInbound}}
          - application: {{this.application}}
      namespace: {{this.namespace}}
      cluster: {{this.cluster}}
      {{/each}}
  secureLogs:
    enabled: true
  kafka:
    pool: {{kafka.pool}}
  liveness:
    path: /bidrag-dokument-arkiv/actuator/health
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /bidrag-dokument-arkiv/actuator/health
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /bidrag-dokument-arkiv/actuator/prometheus
  resources:
    limits:
      memory: 4096Mi
    requests:
      memory: 2560Mi
  ingresses:
  {{#each ingresses as |url|}}
      - {{url}}
  {{/each}}
  env:
  {{#each env}}
      - name: {{@key}}
  value: "{{this}}"
  {{/each}}
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/{{ vault.kvPath }}/srvbdarkiv
        mountPath: /var/run/secrets/nais.io/srvbdarkiv
