name: bidrag-dokument-arkiv
serviceuser: p
ingresses:
  - https://bidrag-dokument-arkiv.nais.adeo.no/
  - https://bidrag-dokument-arkiv.prod-fss.nais.io
kafka:
  pool: nav-prod
env:
  ACCEPTED_AUDIENCE: bisys-p,bidrag-ui-p
  ACCEPTED_SERVICE_USER_AUDIENCE: srvbdarkivering,srvbisys
  ISSO_ISSUER_URL: https://isso.adeo.no:443/isso/oauth2
  STS_ISSUER_URL: https://security-token-service.nais.adeo.no
  ACCESS_TOKEN_URL: https://security-token-service.nais.adeo.no
  DOKARKIV_URL: https://dokarkiv.nais.adeo.no/
  DOKARKIV_PROXY_URL:  https://dokarkivproxy.intern.nav.no
  DOKDISTFORDELING_URL: https://dokdistfordeling.nais.adeo.no
  SAF_URL: https://saf.nais.adeo.no
  OPPGAVE_URL: https://oppgave.nais.adeo.no/api/v1/oppgaver
  OPPGAVE_SCOPE: prod-fss.oppgavehandtering.oppgave
  SAF_SCOPE: prod-fss.teamdokumenthandtering.saf
  DOKARKIV_SCOPE: prod-fss.teamdokumenthandtering.dokarkiv
  TOPIC_JOURNALPOST: bidrag.journalpost
  TOPIC_JOURNALFOERING: teamdokumenthandtering.aapen-dok-journalfoering
  BIDRAG_PERSON_URL: https://bidrag-person.nais.adeo.no
  BIDRAG_ORGANISASJON_URL: https://bidrag-organisasjon.nais.adeo.no
  FEATURE_ENABLED: NONE
vault:
  kvPath: prod
azureAccessInbound:
  - application: bidrag-dokument
    namespace: bidrag
    cluster: prod-fss