name: bidrag-dokument-arkiv
serviceuser: p
ingresses:
  - https://bidrag-dokument-arkiv.nais.adeo.no/
  - https://bidrag-dokument-arkiv.intern.nav.no/
  - https://bidrag-dokument-arkiv.prod-fss.nais.io
kafka:
  pool: nav-prod
env:
  ACCEPTED_SERVICE_USER_AUDIENCE: srvbdarkivering,srvbisys
  STS_ISSUER_URL: https://security-token-service.nais.adeo.no
  ACCESS_TOKEN_URL: https://security-token-service.nais.adeo.no
  DOKARKIV_URL: https://dokarkiv.intern.nav.no/
  DOKARKIV_KNYTT_TIL_SAK_URL: https://dokarkiv.intern.nav.no
  DOKDISTFORDELING_URL: https://dokdistfordeling.intern.nav.no
  SAF_URL: https://saf.nais.adeo.no
  OPPGAVE_URL: https://oppgave.nais.adeo.no/api/v1/oppgaver
  OPPGAVE_SCOPE: prod-fss.oppgavehandtering.oppgave
  SAF_SCOPE: prod-fss.teamdokumenthandtering.saf
  DOKARKIV_SCOPE: prod-fss.teamdokumenthandtering.dokarkiv
  TOPIC_JOURNALPOST: bidrag.journalpost
  TOPIC_OPPGAVE_OPPRETTET: aapen-oppgave-opprettet-v1-prod
  KAFKA_BOOTSTRAP_SERVERS: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443
  TOPIC_JOURNALFOERING: teamdokumenthandtering.aapen-dok-journalfoering
  BIDRAG_PERSON_URL: https://bidrag-person.nais.adeo.no
  PERSON_SCOPE: prod-fss.bidrag.bidrag-person
  BIDRAG_ORGANISASJON_URL: https://bidrag-organisasjon.intern.nav.no
  ORGANISASJON_SCOPE: prod-fss.bidrag.bidrag-organisasjon
  DOKDISTKANAL_URL: https://dokdistkanal.intern.nav.no
  DOKDISTKANAL_SCOPE: prod-fss.teamdokumenthandtering.dokdistkanal
  JAVA_OPTS: -Xmx2048m
vault:
  kvPath: prod
azureAccessInbound:
  - application: bidrag-dokument
    namespace: bidrag
    cluster: prod-fss
  - application: bidrag-ui
    namespace: bidrag
    cluster: prod-fss