name: bidrag-dokument-arkiv
serviceuser: p
ingresses:
  - https://bidrag-dokument-arkiv.nais.adeo.no/
  - https://bidrag-dokument-arkiv.prod-fss.nais.io
kafka:
  pool: nav-prod
env:
  - name: ACCEPTED_AUDIENCE
    value: bisys-p,bidrag-ui-p
  - name: ISSO_ISSUER_URL
    value: https://isso.adeo.no:443/isso/oauth2
  - name: DOKARKIV_URL
    value: https://dokarkiv.nais.adeo.no/
  - name: SAF_GRAPHQL_URL
    value: https://saf.nais.adeo.no/graphql
  - name: ACCESS_TOKEN_URL
    value: https://security-token-service.nais.adeo.no
  - name: TOPIC_JOURNALPOST
    value: bidrag.journalpost
  - name: TOPIC_JOURNALFOERING
    value: teamdokumenthandtering.aapen-dok-journalfoering
  - name: BIDRAG_PERSON_URL
    value: https://bidrag-person.nais.adeo.no
vault:
  kvPath: prod
