server:
  servlet:
    context-path: /bidrag-dokument-arkiv

    
no.nav.security.oidc.issuer.isso.acceptedaudience: ${APP_NAME}-${FASIT_ENVIRONMENT_NAME}
no.nav.security.oidc.issuer.isso.discoveryurl: ${ISSO_ISSUER_URL}/.well-known/openid-configuration
no.nav.security.oidc.issuer.isso.cookiename: bidrag-id-token