server:
  servlet:
    context-path: /bidrag-dokument-arkiv

# OIDC          
no.nav.security.oidc:
  issuers: isso
  issuer:
    isso:
      acceptedaudience: bisys-${FASIT_ENVIRONMENT_NAME}, bidrag-ui-${FASIT_ENVIRONMENT_NAME}, bidrag-dokument-ui-${FASIT_ENVIRONMENT_NAME}, bidrag-q-localhost
      discoveryurl: ${ISSO_ISSUER_URL}/.well-known/openid-configuration
