ACCEPTED_AUDIENCE: bisys-q1,bidrag-ui-feature-q1,bidrag-dokument-ui-q1,bidrag-q-localhost,ida-q
ISSO_ISSUER_URL: http://localhost:8888/isso
ACCESS_TOKEN_URL: https://security-token-service.dev.adeo.no
AKTORREGISTER_URL: https://app-q1.adeo.no/aktoerregister
DOKARKIV_URL: https://dokarkiv-q1.dev.adeo.no
DOKDISTFORDELING_URL: https://dokdistfordeling-q1.dev.adeo.no
DOKARKIV_PROXY_URL: https://dokarkivproxy-q1.dev.intern.nav.no
BIDRAG_PERSON_URL: https://bidrag-person-feature.dev.adeo.no
BIDRAG_ORGANISASJON_URL: https://bidrag-organisasjon-feature.dev.adeo.no
SAF_URL: https://saf-q1.dev.adeo.no
NAIS_APP_NAME: bidrag-dokument-arkiv-feature
TOPIC_JOURNALPOST: bidrag-journalpost
TOPIC_JOURNALFOERING: joark-hendelse
STS_ISSUER_URL: http://localhost:8888/sts
ACCEPTED_SERVICE_USER_AUDIENCE: srvbdarkivering,srvbisys
SRV_BD_ARKIV_AUTH: changme
FEATURE_ENABLED: KAFKA_ARBEIDSFLYT
AZURE_APP_TENANT_ID: 966ac572-f5b7-4bbe-aa88-c76419c0f851
OPPGAVE_URL: https://oppgave-q1.dev-fss-pub.nais.io/api/v1/oppgaver
OPPGAVE_SCOPE: dev-fss.oppgavehandtering.oppgave-q1
SAF_SCOPE: dev-fss.teamdokumenthandtering.saf
ORGANISASJON_SCOPE: dev-fss.bidrag.bidrag-organisasjon-feature
DOKARKIV_SCOPE: dev-fss.teamdokumenthandtering.dokarkiv-q1
KAFKA_GROUP_ID: bidrag-arkiv-consumer
KAFKA_BROKERS: localhost:9092

AZURE_APP_CLIENT_SECRET: changme
AZURE_APP_CLIENT_ID: changeme

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    properties:
      security.protocol: PLAINTEXT
    consumer:
      enableAutoCommit: false
      auto-offset-reset: latest
    listener:
      ackMode: RECORD