name: continious integration
on:
  push:
    branches:
      - '**'

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/bidrag-dokument:${{ github.sha }}

jobs:

  build:
    name: Build with maven and docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '13'
      - run: env
      - uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: navikt/bidrag-actions/setup-maven@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Verify that no dependencies are of type SNAPSHOT
        uses: navikt/bidrag-actions/verify-mvn-dependencies@v1.0.0
      - name: Build & test with maven
        run: mvn -B install
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build --tag ${IMAGE} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}

  deploy_dev:
    runs-on: ubuntu-latest
    name: Deploy docker image to dev
    if: github.ref != 'refs/heads/release'
    needs: build

    steps:
      - uses: actions/checkout@v2
        with:
          path: deploy
      - run: env && ls -all deploy/
      - name: Deploy to dev-fss - namespace q4
        if: github.ref == 'refs/heads/master'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: deploy/nais.yaml
          VAR: namespace=q4,ingress=q4
      - name: Deploy to dev-fss, default namespace
        if: github.ref == 'refs/heads/develop'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: deploy/nais.yaml
          VAR: namespace=default,ingress=''
      - name: Deploy to dev-fss, namespace q1
        if: github.ref != 'refs/heads/develop' && github.ref != 'refs/heads/master'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: deploy/nais.yaml
          VAR: namespace=q1,ingress=q1
      - name: Bump version
        if: github.ref == 'refs/heads/develop'
        run: echo "todo - bump version"

  deploy_prod:
    runs-on: ubuntu-latest
    name: Deploy docker image to prod
    if: github.ref == 'refs/heads/release'
    needs: build

    steps:
      - uses: actions/checkout@v2
        with:
          path: deploy
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prodfss
          RESOURCE: deploy/nais.yaml
          VAR: namespace=default,ingress=''
      - name: tag release
        if: github.ref == 'refs/heads/release'
        run: echo "todo - tag release"
