name: Deploy to prod
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build-deploy:
    name: "Build and deploy to prod"
    permissions:
      contents: "write"
      id-token: "write"
    uses: navikt/bidrag-workflow/.github/workflows/deploy_prod.yaml@main
    with:
      nais_cluster: fss
    secrets: inherit